### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Meeketank** [preethi4848/Mentor-Mate-App#2]
too much errors in it

**Comment by Meeketank** [comment]
This app crashes due to some files are not there

**Comment by preethi4848** [comment]
We did not find any errors, It is running smoothly in my system.
For your reference I have attached demo of the output.
Drive link : https://drive.google.com/file/d/15YrJL-dBhyS_4sqhD9qihPLEu6dBe9qr/view?usp=sharing
